// Package petshop provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package petshop

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AnimalType.
const (
	Dog   AnimalType = "dog"
	Snake AnimalType = "snake"
)

// Valid indicates whether the value is a known member of the AnimalType enum.
func (e AnimalType) Valid() bool {
	switch e {
	case Dog:
		return true
	case Snake:
		return true
	default:
		return false
	}
}

// Defines values for PetStatus.
const (
	Available PetStatus = "available"
	Reserved  PetStatus = "reserved"
	Sold      PetStatus = "sold"
)

// Valid indicates whether the value is a known member of the PetStatus enum.
func (e PetStatus) Valid() bool {
	switch e {
	case Available:
		return true
	case Reserved:
		return true
	case Sold:
		return true
	default:
		return false
	}
}

// AnimalType defines model for AnimalType.
type AnimalType string

// CreatePetRequest defines model for CreatePetRequest.
type CreatePetRequest struct {
	// Metadata Additional pet metadata used by presentation and inventory rules.
	Metadata *Metadata `json:"metadata,omitempty"`
	Name     string    `json:"name"`
	Price    float64   `json:"price"`

	// Status Current inventory status for the pet.
	Status *PetStatus `json:"status,omitempty"`
	Type   AnimalType `json:"type"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Metadata Additional pet metadata used by presentation and inventory rules.
type Metadata struct {
	// Region Region where the pet is available.
	Region               *string           `json:"Region,omitempty"`
	AdditionalProperties map[string]string `json:"-"`
}

// PatchPetRequest defines model for PatchPetRequest.
type PatchPetRequest struct {
	// Metadata Additional pet metadata used by presentation and inventory rules.
	Metadata *Metadata `json:"metadata,omitempty"`
	Name     *string   `json:"name,omitempty"`
	Price    *float64  `json:"price,omitempty"`

	// Status Current inventory status for the pet.
	Status *PetStatus  `json:"status,omitempty"`
	Type   *AnimalType `json:"type,omitempty"`
}

// Pet defines model for Pet.
type Pet struct {
	Id openapi_types.UUID `json:"id"`

	// Metadata Additional pet metadata used by presentation and inventory rules.
	Metadata Metadata `json:"metadata"`
	Name     string   `json:"name"`
	Price    float64  `json:"price"`

	// Status Current inventory status for the pet.
	Status *PetStatus `json:"status,omitempty"`
	Type   AnimalType `json:"type"`
}

// PetStatus Current inventory status for the pet.
type PetStatus string

// UpdatePetRequest defines model for UpdatePetRequest.
type UpdatePetRequest = CreatePetRequest

// PetId defines model for PetId.
type PetId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListPetsParams defines parameters for ListPets.
type ListPetsParams struct {
	// Type Filter pets by animal type.
	Type *AnimalType `form:"type,omitempty" json:"type,omitempty"`

	// Region Filter pets by metadata region.
	Region *string `form:"region,omitempty" json:"region,omitempty"`
}

// CreatePetJSONRequestBody defines body for CreatePet for application/json ContentType.
type CreatePetJSONRequestBody = CreatePetRequest

// PatchPetJSONRequestBody defines body for PatchPet for application/json ContentType.
type PatchPetJSONRequestBody = PatchPetRequest

// UpdatePetJSONRequestBody defines body for UpdatePet for application/json ContentType.
type UpdatePetJSONRequestBody = UpdatePetRequest

// Getter for additional properties for Metadata. Returns the specified
// element and whether it was found
func (a Metadata) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Metadata
func (a *Metadata) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Metadata to handle AdditionalProperties
func (a *Metadata) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["Region"]; found {
		err = json.Unmarshal(raw, &a.Region)
		if err != nil {
			return fmt.Errorf("error reading 'Region': %w", err)
		}
		delete(object, "Region")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Metadata to handle AdditionalProperties
func (a Metadata) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Region != nil {
		object["Region"], err = json.Marshal(a.Region)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'Region': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List pets
	// (GET /pets)
	ListPets(ctx *echo.Context, params ListPetsParams) error
	// Create a pet
	// (POST /pets)
	CreatePet(ctx *echo.Context) error
	// Get a pet
	// (GET /pets/{petId})
	GetPet(ctx *echo.Context, petId PetId) error
	// Partially update a pet
	// (PATCH /pets/{petId})
	PatchPet(ctx *echo.Context, petId PetId) error
	// Update a pet
	// (PUT /pets/{petId})
	UpdatePet(ctx *echo.Context, petId PetId) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListPets converts echo context to params.
func (w *ServerInterfaceWrapper) ListPets(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPetsParams
	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", ctx.QueryParams(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// ------------- Optional query parameter "region" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "region", ctx.QueryParams(), &params.Region, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter region: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListPets(ctx, params)
	return err
}

// CreatePet converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePet(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreatePet(ctx)
	return err
}

// GetPet converts echo context to params.
func (w *ServerInterfaceWrapper) GetPet(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "petId" -------------
	var petId PetId

	err = runtime.BindStyledParameterWithOptions("simple", "petId", ctx.Param("petId"), &petId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter petId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPet(ctx, petId)
	return err
}

// PatchPet converts echo context to params.
func (w *ServerInterfaceWrapper) PatchPet(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "petId" -------------
	var petId PetId

	err = runtime.BindStyledParameterWithOptions("simple", "petId", ctx.Param("petId"), &petId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter petId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchPet(ctx, petId)
	return err
}

// UpdatePet converts echo context to params.
func (w *ServerInterfaceWrapper) UpdatePet(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "petId" -------------
	var petId PetId

	err = runtime.BindStyledParameterWithOptions("simple", "petId", ctx.Param("petId"), &petId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter petId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdatePet(ctx, petId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/pets", wrapper.ListPets, options.OperationMiddlewares["listPets"]...)
	router.POST(options.BaseURL+"/pets", wrapper.CreatePet, options.OperationMiddlewares["createPet"]...)
	router.GET(options.BaseURL+"/pets/:petId", wrapper.GetPet, options.OperationMiddlewares["getPet"]...)
	router.PATCH(options.BaseURL+"/pets/:petId", wrapper.PatchPet, options.OperationMiddlewares["patchPet"]...)
	router.PUT(options.BaseURL+"/pets/:petId", wrapper.UpdatePet, options.OperationMiddlewares["updatePet"]...)

}

type BadRequestJSONResponse Error

type ErrorJSONResponse Error

type NotFoundJSONResponse Error

type ListPetsRequestObject struct {
	Params ListPetsParams
}

type ListPetsResponseObject interface {
	VisitListPetsResponse(w http.ResponseWriter) error
}

type ListPets200JSONResponse []Pet

func (response ListPets200JSONResponse) VisitListPetsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPetsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListPetsdefaultJSONResponse) VisitListPetsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePetRequestObject struct {
	Body *CreatePetJSONRequestBody
}

type CreatePetResponseObject interface {
	VisitCreatePetResponse(w http.ResponseWriter) error
}

type CreatePet201ResponseHeaders struct {
	Location *string
}

type CreatePet201JSONResponse struct {
	Body    Pet
	Headers CreatePet201ResponseHeaders
}

func (response CreatePet201JSONResponse) VisitCreatePetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePet400JSONResponse struct{ BadRequestJSONResponse }

func (response CreatePet400JSONResponse) VisitCreatePetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePetdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreatePetdefaultJSONResponse) VisitCreatePetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetPetRequestObject struct {
	PetId PetId `json:"petId"`
}

type GetPetResponseObject interface {
	VisitGetPetResponse(w http.ResponseWriter) error
}

type GetPet200JSONResponse Pet

func (response GetPet200JSONResponse) VisitGetPetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPet404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPet404JSONResponse) VisitGetPetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPetdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetPetdefaultJSONResponse) VisitGetPetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPetRequestObject struct {
	PetId PetId `json:"petId"`
	Body  *PatchPetJSONRequestBody
}

type PatchPetResponseObject interface {
	VisitPatchPetResponse(w http.ResponseWriter) error
}

type PatchPet200JSONResponse Pet

func (response PatchPet200JSONResponse) VisitPatchPetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPet400JSONResponse struct{ BadRequestJSONResponse }

func (response PatchPet400JSONResponse) VisitPatchPetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPet404JSONResponse struct{ NotFoundJSONResponse }

func (response PatchPet404JSONResponse) VisitPatchPetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPetdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PatchPetdefaultJSONResponse) VisitPatchPetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePetRequestObject struct {
	PetId PetId `json:"petId"`
	Body  *UpdatePetJSONRequestBody
}

type UpdatePetResponseObject interface {
	VisitUpdatePetResponse(w http.ResponseWriter) error
}

type UpdatePet200JSONResponse Pet

func (response UpdatePet200JSONResponse) VisitUpdatePetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePet400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdatePet400JSONResponse) VisitUpdatePetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePet404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdatePet404JSONResponse) VisitUpdatePetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePetdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpdatePetdefaultJSONResponse) VisitUpdatePetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List pets
	// (GET /pets)
	ListPets(ctx context.Context, request ListPetsRequestObject) (ListPetsResponseObject, error)
	// Create a pet
	// (POST /pets)
	CreatePet(ctx context.Context, request CreatePetRequestObject) (CreatePetResponseObject, error)
	// Get a pet
	// (GET /pets/{petId})
	GetPet(ctx context.Context, request GetPetRequestObject) (GetPetResponseObject, error)
	// Partially update a pet
	// (PATCH /pets/{petId})
	PatchPet(ctx context.Context, request PatchPetRequestObject) (PatchPetResponseObject, error)
	// Update a pet
	// (PUT /pets/{petId})
	UpdatePet(ctx context.Context, request UpdatePetRequestObject) (UpdatePetResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListPets operation middleware
func (sh *strictHandler) ListPets(ctx *echo.Context, params ListPetsParams) error {
	var request ListPetsRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListPets(ctx.Request().Context(), request.(ListPetsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPets")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListPetsResponseObject); ok {
		return validResponse.VisitListPetsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreatePet operation middleware
func (sh *strictHandler) CreatePet(ctx *echo.Context) error {
	var request CreatePetRequestObject

	var body CreatePetJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePet(ctx.Request().Context(), request.(CreatePetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreatePetResponseObject); ok {
		return validResponse.VisitCreatePetResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetPet operation middleware
func (sh *strictHandler) GetPet(ctx *echo.Context, petId PetId) error {
	var request GetPetRequestObject

	request.PetId = petId

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPet(ctx.Request().Context(), request.(GetPetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetPetResponseObject); ok {
		return validResponse.VisitGetPetResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PatchPet operation middleware
func (sh *strictHandler) PatchPet(ctx *echo.Context, petId PetId) error {
	var request PatchPetRequestObject

	request.PetId = petId

	var body PatchPetJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PatchPet(ctx.Request().Context(), request.(PatchPetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchPet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PatchPetResponseObject); ok {
		return validResponse.VisitPatchPetResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdatePet operation middleware
func (sh *strictHandler) UpdatePet(ctx *echo.Context, petId PetId) error {
	var request UpdatePetRequestObject

	request.PetId = petId

	var body UpdatePetJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdatePet(ctx.Request().Context(), request.(UpdatePetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdatePet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdatePetResponseObject); ok {
		return validResponse.VisitUpdatePetResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
