# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/refs/heads/main/configuration-schema.json
package: petshop
generate:
  models: true
  echo5-server: true
  strict-server: true
  embedded-spec: false
output: api.gen.go
